export const books = [
  {
    id: 1,
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    publishDate: "1925-04-10",
    pages: 180,
    available: true,
  },
  {
    id: 2,
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    publishDate: "1960-07-11",
    pages: 281,
    available: false,
  },
  {
    id: 3,
    title: "1984",
    author: "George Orwell",
    publishDate: "1949-06-08",
    pages: 328,
    available: true,
  },
  {
    id: 4,
    title: "Pride and Prejudice",
    author: "Jane Austen",
    publishDate: "1813-01-28",
    pages: 279,
    available: true,
  },
  {
    id: 5,
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    publishDate: "1951-07-16",
    pages: 214,
    available: false,
  },
  {
    id: 6,
    title: "Moby-Dick",
    author: "Herman Melville",
    publishDate: "1851-10-18",
    pages: 635,
    available: true,
  },
  {
    id: 7,
    title: "War and Peace",
    author: "Leo Tolstoy",
    publishDate: "1869-01-01",
    pages: 1225,
    available: false,
  },
  {
    id: 8,
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    publishDate: "1937-09-21",
    pages: 310,
    available: true,
  },
  {
    id: 9,
    title: "Crime and Punishment",
    author: "Fyodor Dostoevsky",
    publishDate: "1866-01-01",
    pages: 430,
    available: false,
  },
  {
    id: 10,
    title: "The Lord of the Rings",
    author: "J.R.R. Tolkien",
    publishDate: "1954-07-29",
    pages: 1178,
    available: true,
  },
  {
    id: 11,
    title: "Brave New World",
    author: "Aldous Huxley",
    publishDate: "1932-08-18",
    pages: 268,
    available: true,
  },
  {
    id: 12,
    title: "Jane Eyre",
    author: "Charlotte Brontë",
    publishDate: "1847-10-16",
    pages: 500,
    available: false,
  },
  {
    id: 13,
    title: "Wuthering Heights",
    author: "Emily Brontë",
    publishDate: "1847-12-17",
    pages: 416,
    available: true,
  },
  {
    id: 14,
    title: "The Alchemist",
    author: "Paulo Coelho",
    publishDate: "1988-01-01",
    pages: 208,
    available: false,
  },
  {
    id: 15,
    title: "The Odyssey",
    author: "Homer",
    publishDate: "-800-01-01",
    pages: 541,
    available: true,
  },
  {
    id: 16,
    title: "Les Misérables",
    author: "Victor Hugo",
    publishDate: "1862-01-01",
    pages: 1463,
    available: false,
  },
  {
    id: 17,
    title: "Dracula",
    author: "Bram Stoker",
    publishDate: "1897-05-26",
    pages: 418,
    available: true,
  },
  {
    id: 18,
    title: "Frankenstein",
    author: "Mary Shelley",
    publishDate: "1818-01-01",
    pages: 280,
    available: false,
  },
  {
    id: 19,
    title: "The Picture of Dorian Gray",
    author: "Oscar Wilde",
    publishDate: "1890-07-01",
    pages: 254,
    available: true,
  },
  {
    id: 20,
    title: "Anna Karenina",
    author: "Leo Tolstoy",
    publishDate: "1878-01-01",
    pages: 864,
    available: false,
  },
];
